import { api } from '../services/api.js';
import { Dialog, confirmAction } from '../components/dialog.js';

// Creation asks only for user content; library identity and metadata are generated by AILoom.
export function ManagedDefinition(container, {kind=null, id=null}={}) {
  return new Promise(resolve=>{
    const body=document.createElement('div');
    body.innerHTML=`${id?'':`<label>类型<select data-kind><option value="rule">规则 · 约束 AI 的行为</option><option value="agent">子代理 · 分配专门任务</option></select></label><label>名称<input data-name placeholder="例如 code-review" maxlength="64"></label>`}<label>用途<input data-description placeholder="例如：检查代码中的潜在问题"></label><label>内容<textarea data-content rows="12" placeholder="填写规则或子代理的职责"></textarea></label><p data-error class="field-error" role="alert"></p><footer class="dialog-actions">${id?'<button data-delete class="danger">删除…</button>':''}<button data-save class="primary">保存到资源库</button></footer>`;
    const q=s=>body.querySelector(s);
    let busy=!!id, disposed=false, original='', originalDescription='', fingerprint=null, result=null;
    const modal=Dialog(container,{title:id?`编辑 ${id.split('/').pop()}`:'新建规则 / 子代理',content:body,canClose:()=>!busy,dirty:()=>!result&&(q('[data-content]').value!==original||!!q('[data-name]')?.value||q('[data-description]').value!==originalDescription),onClose:()=>{disposed=true;resolve(result);}});
    if(!id){q('[data-kind]').value=kind||'rule';q('[data-kind]').disabled=!!kind;}
    q('[data-save]').disabled=busy;
    if(id)api.libraryResource(id).then(v=>{if(disposed)return;if(!v.definition)throw Error('无法读取 Rules / Agent 内容');original=v.definition.body;originalDescription=v.definition.description;fingerprint=v.fingerprint;q('[data-content]').value=original;q('[data-description]').value=originalDescription;}).catch(e=>{q('[data-error]').textContent=e.message;}).finally(()=>{busy=false;if(!disposed)q('[data-save]').disabled=!fingerprint;});
    if(id)q('[data-delete]').onclick=async()=>{
      if(busy)return;busy=true;
      try {await api.libraryDelete(id,false);if(!await confirmAction('删除这个能力？正在使用的能力不能删除。',{title:'删除能力',confirmLabel:'删除',destructive:true}))return;await api.libraryDelete(id,true);result={id,deleted:true};modal.close();}
      catch(e){q('[data-error]').textContent=e.message;}finally{busy=false;}
    };
    q('[data-save]').onclick=async()=>{
      if(busy)return;
      busy=true;q('[data-save]').disabled=true;q('[data-error]').textContent='';
      try {
        const content=q('[data-content]').value;
        const saved=id?await api.libraryDefinitionSave(id,{body:content,description:q('[data-description]').value.trim()},fingerprint):await api.libraryCreate({kind:q('[data-kind]').value,name:q('[data-name]').value.trim(),description:q('[data-description]').value.trim(),body:content});
        result={id:id||saved.id};modal.close();
      } catch(e){q('[data-error]').textContent=e.message;}
      finally {busy=false;if(!disposed)q('[data-save]').disabled=false;}
    };
  });
}
